TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += devLakeshore_460.proto

#=======================================
include $(TOP)/configure/RULES
